### ISSUE TITLE
No authorization line in Dev Tools

### ISSUE THREAD

**Issue by Zelatrix** [Dracovian/Discord-Scraper#11]
I logged into my account and opened Developer Tools, but none of the options that appear in the network tab have an "authorization" line. Am I doing something wrong?

**Comment by Dracovian** [comment]
The official Discord API mentions the following:

```
Some API and Gateway versions are now non-functioning, and are labeled as discontinued.
Trying to use these versions will fail and return 400 Bad Request.
```

I've heard of people getting HTTP 418 errors when being ratelimited but this script doesn't hit that ratelimit (from what I've seen when testing it).

I've heard of people getting HTTP 403 errors but that's when they put in the wrong authorization token, use an expired authorization token, or forget to add an authorization token to the discord.json file.

I've heard of people getting HTTP 404 errors but the script shouldn't produce those errors unless you're scraping from a channel that has content that links to sites that no longer store said contents or if the content is no longer accessible due to being removed over time.

I've not heard of any other 400 error occurring aside from those three, could you confirm if your 400 errors are any of those three mentioned above?

**Comment by Zelatrix** [comment]
The errors that I'm getting are HTTP: 400 - BAD REQUEST errors. I followed the tutorial so I'm not sure what I could have done wrong.

**Comment by Dracovian** [comment]
Hmm... are you by any chance attempting to scrape from any channels or servers that are linking to external resources?

I've not gotten any HTTP 400 errors when running this script using the latest versions of 2.7 and 3.7, but then again the servers I'm testing out have a mix of content uploaded directly to Discord and content that are linked from external sources.

Which version of Python are you using and are you using the most recent version of this script?

**Comment by Zelatrix** [comment]
They might have external links, possibly. I'm using v.3.7.3 and I think I'm running the most recent version, if I'm correct. Is there a way to confirm this?

**Comment by Dracovian** [comment]
I changed the JSON layout between the previous version and the recent version of this script:

Here's the JSON for this current version: https://github.com/Dracovian/Discord-Scraper/blob/master/discord.json

Here's the JSON for the previous version: https://github.com/Dracovian/Discord-Scraper/blob/a4ee8161772c9e054b8392bf9fff1f89d1ef662a/discord.json

**Comment by Zelatrix** [comment]
I have the latest versionst of the JSON, I believe.

**Comment by Dracovian** [comment]
I'll see if I can't figure out a way to get embedded contents more efficiently, in the meantime see if you can't get the script to work on a test server to make sure that this is an issue with external contents and not an issue with the script in general.

**Comment by Zelatrix** [comment]
I tested it on a test server and still the same errors.

**Comment by pyrate01** [comment]
I've narrowed this issue down to the json file. You need at least one DM ID, and remove the other example. This cleared up the 400 error. 

However, I began to get 404 errors, so getting somewhere... maybe? This is just one example of what the link requested. I asked it nicely to show me the link form that was returning 404. 
I suspect it has something to deal with passing the query... but this process eludes my knowledge, momentarily. 

Received HTTP 404 error: NOT FOUND
https://discordapp.com/api/v6/channels/279488863720833025/messages/search?min_id=601986642739200000&max_id=602349030604800000&&has=image&has=file&has=embed&has=link&has=video&include_nsfw=true

**Comment by vinnytroia** [comment]
I am having the exact same issue as pyrate01 -- i initially had a 400 error - i fixed by including 1 DM - then i get a 400 error. 

Any ideas about how to debug or fix?

**Comment by Dracovian** [comment]
Okay I believe that I found a solution to the HTTP 400 issue.

This is possibly due to the change that Cloudflare made to its reverse proxy that checks the request headers for invalid or unneeded headers. If any are found then it will return a 400 error.

So the solution to that is to reduce the sent headers to remove the offending headers that are making Cloudflare's reverse proxy servers throw the error.

The solution to the 404 error is still unknown since I don't have authorization to view the image (I'm not in the same server to be able to view the image) and thus I can't fully determine why it's throwing a 404 error aside from an incorrect direct message channel id.

I'll put in a full tutorial on how to grab the proper channel ID for a direct message. Right now I'm updating the script to hopefully fix some of the other issues.

**Comment by vinnytroia** [comment]
any word on these updates?

**Comment by Dracovian** [comment]
@vinnytroia The experimental branch script is still unable to grab embedded images (still returning an HTTP 403 error depending on the site hosting the image(s)).

I have fixed the HTTP 400 error but there are still issues with grabbing textual data and it's going to take a while to fix as I'm likely going to have to overhaul this script again. I have opened up several TODO issues which should serve as a short-term roadmap for this project.

**Comment by tntpower10** [comment]
So when can we expect that the HTTP 400 error will be fixed?

**Comment by Dracovian** [comment]
@tntpower10 You can test the experimental branch to see if it still produces HTTP 400 errors when scraping, you don't have to change your discord.json file contents to run the experimental branch script.

If it is still throwing 400 errors, then please make a new issue for the experimental script so that I can determine if the Cloudflare issue hasn't yet been resolved or if there's another source for the 400 errors.

**Comment by vinnytroia** [comment]
Hi. so i was able to fix the 400 errors without any code updates. The JSON in the example is malformed which is causing the problem. Once i fixed this, the errors went away. 

Try this: 


    "token": "xxx",
    "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
    "query": {
	"images": false,
        "files" : false,
        "embeds": false,
        "links" : false,
        "videos": false,
        "nsfw"  : true
    },
    "types": {
	"images": false,
        "videos": false,
        "files" : false,
        "text"  : true
    },
    "directs": {
        "Channel1": "xxx"
    },
    "servers": {
        "xxx": [
            "xxx"
        ]
    }
}

**Comment by Dracovian** [comment]
@vinnytroia The JSON file is parsed perfectly fine, so it shouldn't be an issue with the formatting of the JSON file.

I don't know if there's some strange issue with the MacOS version of Python regarding the formatting of a JSON file, but under Linux and Windows the JSON file in the example parses just fine:

![Screenshot_2019-10-01_14-44-57](https://user-images.githubusercontent.com/25242161/65994951-17438000-e45a-11e9-9789-17c29fc857b2.png)

Now if having to grab videos and files is causing the text grabbing to fail with HTTP 400 errors, then that's definitely something I have to look into since I was able to remove any HTTP 400 errors from my test runs with the changes I made to the script in the experimental branch.

Check the TODO issues I've made to see what I plan on adding to the experimental branch script regarding text scraping and other odds-and-ends that will come in handy in the future.

**Comment by bydioeds** [comment]
The issue is in
```json
"directs": {
		"DM 1 Name": "DM 1 ID",
		"DM 2 Name": "DM 2 ID"
	},
```

you need to remove all the example code `"DM 1 Name": "DM 1 ID"` and `"DM 2 Name": "DM 2 ID"` that was the issue for me.
is the same for 
```json
"servers": {
		"Server 1 ID": [
			"Server 1 Channel 1 ID",
			"Server 1 Channel 2 ID"
		],
		"Server 2 ID": [
			"Server 2 Channel 1 ID",
			"Server 2 Channel 2 ID"
		]
	}
```

**Comment by Dracovian** [comment]
Hmm... I suppose I might have to opt for a different JSON layout or a different JSON parsing method for the updated code.

Keep an eye out on the experimental branch since that's where my theoretically functioning code will be until I confirm it to be functioning.

Whenever I do confirm it to be working, then I'll merge the branches again and it'll be the up-to-date script yet again.

**Comment by Dracovian** [comment]
It also appears that the 401 issue is due to the fact that the attachment URLs are redirects. So the fix there is to opt for the Proxy URLs instead.

I've made this change in the experimental branch script. To grab that script you can do this:
```
git clone https://github.com/Dracovian/Discord-Scraper
cd Discord-Scraper
git checkout experimental
```

And make sure to modify the contents of the JSON file accordingly afterwards since it should remove the master branch's contents for the experimental branch's contents **(back up your scrapes beforehand)**
